# Generated by Django 3.2 on 2021-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=250)),
                ('doc', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
    ]
